name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shared:
    uses: juanmanuel-tirado/ci-workflows/.github/workflows/python-ci.yml@7b6f7155fd88f3f90662e54fb098d5d78ec43982
    secrets: inherit  
