name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shared:
    uses: juanmanuel-tirado/ci-workflows/.github/workflows/python-ci.yml@e91a1fba1497a080ff851ff91851bb8c5322732f
    secrets: inherit  
