name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shared:
    uses: pantos-io/ci-workflows/.github/workflows/python-ci.yml@84c18c1b5bf447e4a02f94c45c5266abab52bd55
    secrets: inherit  
